<div class="col-xs-12">

<div class="alert-danger title-aviso">
<div class="row"> 
			<div class="col-md-12">
				<h4 class="title-termino"><center> 
				<b> 
				Reglas de Acceso 
				<br>
				Si usted es menor de 18 años, sin excepción, debe salir de la página de CumanaX.com.ve haciendo click aquí. 
</b></center> </h4> </div> 

			<div class="col-md-12">
			<center><a  class="btn btn-default" id="btn_registrar" href="http://www.google.com">Salir</a> </center> <br>
			</div> 

  



</div>

 
   
	<div class="col-md-10 col-md-offset-1 ">
	<div class="row">
	<div class="col-md-12 title-termino "> <br> <br><center> <b>Antes de ingresar a la página de CumanaX.com.ve, usted debe leer atentamente los siguientes Términos y Condiciones: </b> </center></div>
	<div class="col-md-12 title-termino">
	<br> <br>
<p>
<b>Nota:</b> Al ingresar usted está aceptando los Términos y Condiciones aquí establecidos. Si no está de acuerdo, no debe ingresar ni utilizar dicha página. </p> 

    <p><b>1.- PROHIBICIÓN ACCESO DE MENORES:</b> </p>
<p>
    En la página de CumanaX.com.ve se publica texto y fotografía exclusivamente para adultos, por tanto, sólo deben ingresar personas mayores de 18 años.
    El ingreso de menores de edad a esta página, es de exclusiva responsabilidad de los padres, representantes o responsables.
    Es deber de los padres orientar la conducta de sus hijos menores de edad controlando o evitando el acceso a estas páginas mediante programas de protección como Surf Watch, Net Nanny o Cyber Patrol, a los cuales estamos registrados, así como educándolos adecuadamente a que respeten la naturaleza de estas páginas.</p>
<p>
    <b>2.- BIENES Y SERVICIOS PROHIBIDOS: </b></p>
<p>
    La página de CumanaX.com.ve se acoge a la prohibición que implique pornografía infantil, prostitución infantil, explotación sexual infantil o incluyan la mención en singular o plural de "niña", "niño" y/o "adolescente"; y/o que presenten apología a la violencia o al delito; y/o que inciten a la discriminación, al odio o racismo.</p>

   <p> <b>3.- LIMITACIÓN DE RESPONSABILIDAD POR CONTENIDO.- </b></p>
<p>
    La página de CumanaX.com.ve es exclusivamente una Guía Publicitaria, por ello, la responsabilidad de la página de CumanaX.com.ve se limita a informar.<br> <br>

    Todo contenido de los avisos (texto y fotografía) que se publican en la página de CumanaX.com.ve son de la única y exclusiva responsabilidad del anunciante y de ninguna manera la empresa conoce, participa o interfiere en las actividades que realiza el anunciante.<br> <br>

    La empresa no se hace responsable por la exactitud, veracidad, fidelidad o legalidad del contenido de los avisos.
<br> <br>
    Es responsabilidad de la parte interesada hacer las averiguaciones correspondientes sobre el origen, características, condición, funcionamiento y demás propiedades inherentes a los contactos ofrecidos por los anunciantes.<br> <br>

    La página de CumanaX.com.ve no guarda ningún tipo de relación laboral con las personas naturales o jurídicas que aquí se publicitan. Es de la exclusiva responsabilidad del anunciante el personal que tenga empleado. En consecuencia, estarán a cargo de este todos los pagos a que hubiere lugar, de conformidad con la legislación laboral que resultare aplicable según el caso, sin que tuviere los creadores, los diseñadores y/o los propietarios de la página de CumanaX.com.ve, ningún tipo de responsabilidad u obligación frente a dicho personal.
<br> <br>
    Con el acceso a la página, el usuario declara estar conforme con lo mencionado y exonera a la página de CumanaX.com.ve de cualquier responsabilidad legal que pudiera derivarse de los contactos originados en este sitio Web.
</p> 

<p><b> En virtud de lo antes expresado, declaro que:</b></p>

      <p>
				</br>	
			   	♠ Tengo más de 18 años y tengo capacidad legal para visualizar la publicidad ofrecida en esta página.
			    No permitiré acceder a ninguna persona menor de 18 años a la página de CumanaX.Com.Ve.
				</br></br>
			    ♠ El usuario de la página de <b>CumanaX.com.ve</b>, entiende y acepta la responsabilidad por sus propias acciones y conductas, así como las de sus hijos menores transgresores por su no diligencia y cuido.
				</br></br>
			    ♠ Ingreso a la página de <b>CumanaX.com.ve</b> por mi decisión voluntaria y personal porque quiero ver la publicidad que en ella se publica y con mi declaración de voluntad, no considero ofensivas o lesivas las imágenes o mensajes que pudiera encontrar en la página de <b>CumanaX.com.ve</b>.
				</br></br>
			    ♠ Soy exclusivamente responsable y libero a la página de CumanaX.Com.Ve de toda responsabilidad relacionada con la exactitud, veracidad, fidelidad o legalidad del contenido de la publicidad.
			    Entiendo y acepto que la página de <b>CumanaX.com.ve</b> se limita a publicar.
				</br></br>
			    ♠ El diseño general de estas páginas son propiedad exclusiva y absoluta de los creadores de la página de <b>CumanaX.com.ve</b> y en ningún momento y bajo ningún concepto podrán ser utilizadas sin previa autorización por escrito sus creadores.
				</br></br>
			    ♠ Los creadores y los propietarios de la página de CumanaX.Com.Ve, aportan las normas aquí señaladas, liberándose así como consecuencia de acción u omisión de los usuarios, de toda obligación y/o responsabilidad legal.
				<br></br></p>
				<center> <b> Si Acepta los Terminos Condiciones. haga click en el siguiente boton. </b> <br>  <br><a  class="btn btn-default" id="btn_registrar" href="<?php echo BASE_URL;?>principal">Entrar</a> </center><br></br>
	</div>	
	</div>

	
	
        
	</div>
</div>

</div>