<div class="col-xs-12">

<div class="alert-danger title-aviso"><h3 class="title1"> <center> <b> AVISO LEGAL </b></center></h3></div>

    <div class="row">
   
	<div class="col-md-10 col-md-offset-1 ">
	
	<div class="col-md-12 terminos"> 
             <div class="row"> 
			<div class="col-md-12">
				<p>
				 <center><h4>  <b>Usted debe tener 18 años de edad o más para entrar.  </b> </h4><br>
Estas páginas web están destinadas solamente a adultos. El sitio web <b>www.orientex.com.ve</b> reconoce la necesidad de los padres de evitar el acceso de sus niños a cierto contenido presente en Internet, por lo que sugerimos el uso de productos de protección como <b>WebSense, Net Nanny o Cyber Patrol</b> a los cuales estamos registrados.</center>
				<br>
			 <br>  <center>  Para entrar ENTRAR presione el siguiente botón. </b> <br></p><center>
			</div>
			<div class="col-md-12">
				<center><a  class="btn btn-default" id="btn_registrar" href="<?php echo BASE_URL;?>legal">Entrar</a> </center> 
			</div>
			</div>
              
        </div>
        
	</div>
    </div>


</div>