<div class="col-xs-12">

<div class="alert-danger title-aviso">
<div class="row"> 
			<div class="col-md-12">
				<h4 class="title-termino"><center> 
				<b> 
				Anunciate
				<br>
			 
</b></center> </h4> </div> 
</div>
</div>

 
   
	<div class="col-md-10 col-md-offset-1 ">
	<div class="row">
	<div class="col-md-12 title-termino "> <br> <br><center> <b>¿Deseas publicarte en Cumanax.com.ve? </b> </center></div>
	<div class="col-md-12 title-termino "> <br> <br><center> <b> ¿Que esperas? Contacte con nosotros lo mas pronto posible. <br>
Envie un correo electrónico a cumanax@gmail.com o llame (o mande un mensaje de texto): </b> </center></div>
<div class="col-md-12 title-termino "><center> <b> <h3>0 (424) 848.68.69 </h3>
Lunes a Viernes: 9am a 4pm.
 </b> </center></div>

 <div class="col-md-12 title-termino "><br> <br><center> <b>
Cumanax.com.ve es exclusivamente una guía publicitaria. Todo su contenido es de única y exclusiva responsabilidad de los anunciantes y de ninguna manera la
 <br>
 empresa conoce, participa o interfiere en forma o manera alguna en las actividades que estos realizan.
 </b> </center></div>


 <div class="col-md-12 title-termino "> <br><center> <b> <u>
No llame a este teléfono a menos que quiera anunciarse en Cumanax.com.ve
 </u>
 </b> </center></div>


 <div class="col-md-12 title-termino "><center> <b> <h3>¡Te esperamos! </h3>
 </b> </center></div>

	
	</div>

	
	
        
	</div>
</div>