<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
	<div class="header-titulos">banco(<?php if(isset($this->accionn)){echo $this->accionn;} ?>)</div>
	<section>
		<form id="form_banco">
		<input value="<?php if(isset($this->banco)){echo $this->banco->_id;} ?>" type="hidden" id="id" name="id" ></input>
		<input value="<?php if(isset($this->accionn)){echo $this->accionn;} ?>" type="hidden" id="accion" name="accion" ></input>
			<ul>
				<li>
					<h2>banco</h2>
					<span>* datos requeridos </span>
				</li>
				<li>
					<label>nombre</label>
					<input value="<?php if(isset($this->banco)){echo $this->banco->_nombre;} ?>" type="text" id="nombre" name="nombre" placeholder="nombre"></input>
				</li>
				<li>
					<label>tipo de cuenta</label>
					<input value="<?php if(isset($this->banco)){echo $this->banco->_tipo_cta;} ?>" type="text" id="tipo_cta" name="tipo_cuenta" placeholder="tipo_cuenta"></input>
				</li>
					<li>
					<label>numero de cuenta</label>
					<input value="<?php if(isset($this->banco)){echo $this->banco->_nro_cta;} ?>" type="text" id="nro_cta" name="nro_cuenta" placeholder=""></input>
				</li>
				<li>
					<label>direccion</label>
					<input value="<?php if(isset($this->banco)){echo $this->banco->_direccion;} ?>" type="text" id="direccion" name="direccion" placeholder="direccion"></input>
				</li>
				<li>
					<label>saldo</label>
					<input value="<?php if(isset($this->banco)){echo $this->banco->_saldo;} ?>" type="text" id="saldo" name="saldo" placeholder="saldo"></input>
				</li>
				<li>
					<label>moneda</label>
					<input value="<?php if(isset($this->banco)){echo $this->banco->_moneda;} ?>" type="text" id="moneda" name="moneda" placeholder="moneda"></input>
				</li>
				
				<li class="libtn">
					<button class="btn btn-success" id="<?php if(isset($this->accionn)){echo $this->accionn;} ?>" type="button" >guardar</button>
					<button class="btn btn-success" type="button" onclick="history.back(1)">atras</button>
				</li>
			</ul>
		</form>
	</section>

	<?php if (isset($this->accionn) && $this->accionn=='detallar'): ?>
<section id="chequera">
			<div class="header-titulos">chequeras 
			<div id="agregar_cheke_area"><span id="agregar_chek" class="glyphicon glyphicon-plus" aria-hidden=true>agregar</span></div>
			

			</div>
				<table class="">
					<tr>
						<td>
							nro
						</td>
						<td>
							id
						</td>
						<td>
							codigo
						</td>
						<td>
							(desde-hasta)
						</td>
						<td class="acction" >
							acciones
						</td>
					</tr>
					
					<?php for ($i=0; $i < count($this->banco->_chequera) ; $i++): ?>
						<tr>
							<td>
								<?php echo $i ?>
							</td>
							<td>
								<?php echo $this->banco->_chequera[$i]->_id; ?>
							</td>
							<td>
								<?php echo $this->banco->_chequera[$i]->_codigo; ?>
							</td>
							<td>
								<?php echo "(".$this->banco->_chequera[$i]->_desde."-".$this->banco->_chequera[$i]->_hasta.")"; ?>
							</td>
							<td class="acction">
								
						<span id="editar_chequera" data-id="<?php echo $this->banco->_chequera[$i]->_id; ?>" class="glyphicon glyphicon-pencil" aria-hidden=true></span>
						<span id="eliminar_chequera" data-id="<?php echo $this->banco->_chequera[$i]->_id; ?>" class="glyphicon glyphicon-trash" aria-hidden=true></span>
						

							</td>
						</tr>
						<tr>
							<td colspan="5">
								<table>
								
									
									<?php for ($j=0; $j <  count($this->banco->_chequera[$i]->_cheques); $j++): ?>
										<tr>
										<td colspan="6"> cheque nro: <?php echo $this->banco->_chequera[$i]->_cheques[$j]['id_cheque'];  ?></td>
										</tr>
										<tr>
										<td>orden de pago</td>
										<td>fecha de emicion</td>
										<td>descripcion</td>
										<td>fecha de liberacion</td>
										<td>cantidad</td>
										<td>cancelar</td>
									</tr>
										
										<tr>
										<td><?php echo $this->banco->_chequera[$i]->_cheques[$j]['id_orden_de_pago']; ?></td>
										<td><?php echo $this->banco->_chequera[$i]->_cheques[$j]['fecha_emicion']; ?></td>
										<td><?php echo $this->banco->_chequera[$i]->_cheques[$j]['descripcion']; ?></td>
										<td><?php echo $this->banco->_chequera[$i]->_cheques[$j]['fecha_liberancion']; ?></td>
										<td><?php echo $this->banco->_chequera[$i]->_cheques[$j]['cantidad']; ?></td>
											<td>
												<span id="cancelar_cheque" data-id="<?php echo $this->banco->_chequera[$i]->_cheques[$j]['id_cheque']; ?>" class="glyphicon glyphicon-remove" aria-hidden=true></span>
											</td>
									</tr>
								<?php endfor; ?>
								</table>
							</td>
						</tr>
					<?php endfor; ?>
					
					<?php //print_r($this->banco); ?>

				</table>
</section>


	<?php endif; ?>


</div>



<section id="ventana_capa" class="hidden">
	<div id="ventana" >
		<form id="form_chequera">
			<input value="<?php if(isset($this->banco)){echo $this->banco->_id;} ?>" type="hidden" id="" name="" ></input>
			<input value="<?php if(isset($this->accionn)){echo $this->accionn;} ?>" type="hidden" id="" name="" ></input>
				<ul>
					<li>
						<h2>chequera</h2>
						<span>* datos requeridos </span>
					</li>
					<li>
						<input value="" type="hidden" id="chek_accion"></input>
					</li>
					<li>
						<label>codigo</label>
						<input value="" type="text" id="chek_codigo" name="chek_codigo" placeholder="chek_codigo"></input>
					</li>
					<li>
						<label>desde</label>
						<input value="" type="text" id="chek_desde" name="chek_desde" placeholder="chek_desde"></input>
					</li>
					<li>
						<label>hasta</label>
						<input value="" type="text" id="chek_hasta" name="chek_hasta"></input>
					</li>
					
					
					<li class="libtn">
						<button class="btn btn-success" id="chek_guardar" type="button" >guardar</button>
						<button class="btn btn-success" id="_cheque_cerrar" type="button">cerrar</button>
					</li>
				</ul>
		</form>
	</div>
</section>