<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
	<div class="header-titulos">Cuentas bancarias</div>
	<section id="busqueda">
		<div id="buscar">
		<form>
		<label>Buscar</label>
			<input type="text" class=""></input>
		</form>
		
			
		</div>
		
	</section>
	<section id="tabla">
	<table class="">
		
				<tr class="">
					<td>
						nro
					</td>
					<td>
						Nombre
					</td>
					<td>
						tipo de cuenta
					</td>
					<td>
						saldo
					</td>
					<td class="acction">
						Acciones
					</td>
			    </tr>
		
				<?php for ($i=0; $i < count($this->banco) ; $i++) : ?>
				<tr>
					<td>
						<?php echo $this->banco[$i]['id_banco']; ?>
					</td>
					<td>
						<?php echo $this->banco[$i]['nombre']; ?>
					</td>
					<td>
						<?php echo $this->banco[$i]['tipo_cta']; ?>
					</td>
					<td>
						<?php echo number_format($this->banco[$i]['saldo'],2,',','.').$this->banco[$i]['moneda']; ?>
					</td>
					<td class="acction">
						<span id="editar" data-id="<?php echo $this->banco[$i]['id_banco']; ?>" class="glyphicon glyphicon-pencil" aria-hidden=true></span>
						<span id="eliminar" data-id="<?php echo $this->banco[$i]['id_banco']; ?>" class="glyphicon glyphicon-trash" aria-hidden=true></span>
						<span id="ver" data-id="<?php echo $this->banco[$i]['id_banco']; ?>" class="glyphicon glyphicon-eye-open" aria-hidden=true></span>
						<span id="depocitar" data-id="<?php echo $this->banco[$i]['id_banco']; ?>" class="glyphicon glyphicon-download-alt" aria-hidden=true></span>

					</td>
			    </tr>
				<?php endfor; ?>
			

		
			
				<tr>
					
					<td colspan="5">
					
					</td>
					
			    </tr>
	</table>
	</section>
	<section id="botonera">
		
		<button type="button" class="pag" data-pag="<?php echo "1"; ?>"><<</button>

			<?php for ($i=$this->intervalo['inicio']; $i <= $this->intervalo['fin'] ; $i++):?>

			<button type="button" class="pag <?php echo $retVal = ($this->intervalo['pagina']==$i) ? 'pag_select' : '' ; ?>"  data-pag="<?php echo $i; ?>"><?php echo $i; ?></button>

			<?php endfor; ?>

		<button type="button" class="pag" data-pag="<?php echo $this->intervalo['total_pagina'];  ?>">>></button>
	</section>
	<button class="btn btn-success btn-atras" type="button" onclick="history.back(1)">atras</button>
					



</div>