<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
	<div class="header-titulos">Reportes </div>





	<div class="menu_repor" >
		<div class="enlace_repor" data-nombre="proveedor">balance cuentas por pagar</div>
		<div class="enlace_repor" data-nombre="transacciones">reportes transacciones</div>
		<div class="enlace_repor" data-nombre="cheque">cheques</div>
		<div class="enlace_repor" data-nombre="retencion">comprobante de retencion</div>
		<div class="enlace_repor" data-nombre="or_pa">orden de pago</div>
		<div class="enlace_repor" data-nombre="banco_repor">reporte bancario</div>
		

	</div>
	<div class="area_campo" >
		<div class="header-titulos">filtros </div>
		<div id="contenido">
		<p>seleccione una opcion¡¡ </p>
	</div>		
	</div>
</div>
