<div class="col-xs-12">


  <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
              <div><h3 class="title1"> <center> Registro de NiñasX</center></h3></div>
        <form>
          <div class="form-group">
            <label for="exampleInputEmail1">Nombre Artistico</label>
            <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre Artistico">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Fecha de Nacimiento</label>
            <input type="text" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" placeholder="DD/MM/AA">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Medidas</label>
            <input type="text" class="form-control" id="medidas" name="medidas" placeholder="Medidas">
          </div>
           <div class="form-group">
            <label for="exampleInputEmail1">Color de piel</label>
            <input type="text" class="form-control" id="color_piel" name="color_piel" placeholder="Color de piel">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Color de cabello</label>
            <input type="email" class="form-control" id="color_cabello" name="color_cabello" placeholder="Color de cabello">
          </div>
            <div class="form-group">
            <label for="exampleInputEmail1">Color de Ojos</label>
            <input type="email" class="form-control" id="color_ojos" name="color_ojos" placeholder="Color de Ojos">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Videos</label>
            <input type="file" class="form-control" id="password" name="password" >
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Fotos</label>
            <input type="file" class="form-control" id="confirmar_password" name="confirmar_password" placeholder="">
          </div>
          
          <center> <button type="submit" class="btn btn-default">Registrar</button> </center>
        </form> 
            
        </div>
    </div>
</div>

</div>







  




