
<div class="col-md-8 col-md-offset-2">
	<div>registro</div>
	<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus culpa, sed, tempora nobis sequi explicabo ab. Labore quibusdam aspernatur porro omnis totam nulla impedit! Dolor libero laudantium cupiditate, consequatur saepe?
	<div>
	<a href="<?php echo BASE_URL ?>registro/nenas">publicacion</a><br><br>
	
	<a href="<?php echo BASE_URL ?>registro/agencias">agencias</a></div>
	</div>
	
</div>
