<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
	<div class="header-titulos">Gestion de ordenes de pago</div>
	
<section id="orden_de_pago_">
	


	<form id="form_orden_de_pago">
		
			<ul>
				<li>
					<h2>Orden de pago</h2>
					<span>* datos requeridos </span>
				</li>
				<li>
					<label>proveedor</label>
					<input value="" type="text" id="proveedor" name="proveedor" placeholder="">
				</li>
				<li class="lklk">
					<label>factura</label>
					<select id="factura_select">
						<option value="">--seleccione--</option>
					</select>
				</li>
				<li class="lklklk">
					<div id="area_proveedor" class="area">
							<div class="item">Beneficiario
							</div>
							<div class="item">:
							</div>
							<div class="item">Nombre
							</div>
							<div class="item">:
							</div>
							<div class="item">RIF
							</div>
							<div class="item">:
							</div>
							<div class="item">Contacto
							</div>
							<div class="item">:
							</div>
							<div class="item">Diriccion
							</div>
							<div class="item">:
							</div>
							<div class="item">Tipo de credito
							</div>
							<div class="item">:
							</div>
							<div class="item">Porcentaje de retencion
							</div>
							<div class="item">:
							</div>
							<div class="item">Telefono
							</div>
							<div class="item">:
							</div>
					</div>
					<div id="area_factura" class="area">
							
							<table>
								<tr>
									<td colspan="2">
										nro control
									</td>
									<td colspan="2">
										 elavoracion
									</td  >
									<td colspan="2">
										 recepcion
									</td>
									<td colspan="2">
										 vence
									</td>
								</tr>
								<tr>
									<td colspan="2">
										&nbsp;
									</td>
									<td colspan="2">
										 &nbsp;
									</td>
									<td colspan="2">
										 &nbsp;
									</td>
									<td colspan="2">
										 &nbsp;
									</td>
								</tr>
								<tr>
									
									<td>
										cantidad
									</td>
									<td>
										descuento
									</td>
									<td>
										sub total
									</td>
									<td>
										iva
									</td>
									<td>
										total
									</td>
									<td>
										ret.iva
									</td>
									<td>
										neto a pagar
									</td>
									<td>
										saldo pendiente
									</td>
								</tr>
								<tr>
									
									<td>
										&nbsp;
									</td>
									<td>
										&nbsp;
									</td>
									<td>
									&nbsp;
									</td>
									<td>
										&nbsp;
									</td>
									<td>
										&nbsp;
									</td>
									<td>
									&nbsp;
									</td>
									<td>
										&nbsp;
									</td>
									<td>&nbsp;
										
									</td>
								</tr>
							</table>

					</div>
				</li>
			
				
				<li class="libtn">
					<button class="btn btn-success" id="guardar_orden_de_pago" type="button" >guardar</button>
					<button class="btn btn-success" type="button" onclick="history.back(1)">atras</button>
				</li>
			</ul>
		</form>

















</section>


</div>