<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
	<div class="header-titulos">Ordenes de pagos generadas</div>
	


<?php if(!empty($this->orden)): ?>

		<?php for ($i=0; $i <count($this->orden) ; $i++):?>
			<table>
		<tr >
		<td>nro orden de pago : <?php echo $this->orden[$i]->_id ?></td>
		<td>fecha de emicion : <?php echo $this->orden[$i]->_fecha_emicion ?></td>
		<td>nro factura : <?php echo $this->orden[$i]->_id_factura ?></td>
		<td>nro control : <?php echo $this->orden[$i]->_factura->_nro_control ?></td>
		<td>accion</td>
		</tr>

		<tr >
		<td>total a pagar</td>
		<td>descuento</td>
		<td>abono</td>
		<td>saldo pendiente</td>
		<td rowspan="2">
			
			<span id="pagar" data-id="<?php echo $this->orden[$i]->_id ?>" class="glyphicon glyphicon-usd" aria-hidden="true"> Pagar </span>


		</td>
		
		</tr>
		<tr >	

		<?php  

			$descuentos=0;



		for ($j=0; $j < count($this->orden[$i]->_factura->_descuentos) ; $j++) { 
			
			$descuentos+=$this->orden[$i]->_factura->_descuentos[$j]->_cantidad;
			


		} ?>



		<td><?php echo ($this->orden[$i]->_factura->_total-$this->orden[$i]->_factura->_retencion->_retencion) ?></td>
		<td><?php echo $descuentos ?></td>



		<?php 


		$pago=0;

			for ($j=0; $j < count($this->orden[$i]->abonos) ; $j++) { 
				
			
			
			  	$pago+=$this->orden[$i]->abonos[$j]->_cheque->_cantidad;
			
		
				$pago+=$this->orden[$i]->abonos[$j]->_transferencia->_cantidad;
			

		}

		




		 ?>

		<td ><?php echo $pago ?></td>
		



		<td ><?php echo (($this->orden[$i]->_factura->_total-$this->orden[$i]->_factura->_retencion->_retencion)-($pago))-$descuentos; ?></td>
		</tr>
		</table>


		<?php endfor; ?>

<?php else: ?>


	<p class="msj">
			
			no hay prden de pago pendiente por aprobacion... consulte con su asistente¡¡¡ 

	</p>

<?php endif; ?>






























</div>



























<div id="orden_de_pago" class="hidden">
		<div class="header-titulos">completar orden de pago</div>
		<div id="datos_factura">
		<div class="header-titulos">datos de la factura <div id="descuento_modal">aplicar descuentos</div></div>
			
		</div>
		<div id="datos_orden_de_pago">
		<div class="header-titulos">datos de la orden de pago</div>
			
		</div>
		<div class="header-titulos" style="float: left; width: 100%">datos bancarios</div>
<div>
	<form id="form_orden_de_pago">

		



		
			<ul>
				<li>
					<label>Banco</label>
					<select id="banco" >
						<option value="no" >--seleccione--</option>
							
							<?php for ($i=0; $i < count($this->banco)  ; $i++):?>

								<option value="<?php echo $this->banco[$i]['id_banco'] ?>"><?php echo $this->banco[$i]['nombre']."-".$this->banco[$i]['tipo_cta']."-".$this->banco[$i]['saldo'] ?></option>

							<?php endfor; ?>

					</select>
				</li>
				<li>
					
					<label>cantidad a pagar</label> 
					<input type="text" id="cantidad_a_pagar" disabled="disabled">
					
			
				</li>	
				
				<li>
					<label>tipo de pago</label>
					<select id="tipo_pago" disabled="disabled">
						<option value="" >--seleccione--</option>
						<option value="transferencia" >transferencia</option>
						<option value="cheque" >cheque</option>
					</select>
				</li>
				
				<li class="libtn">
					<button class="btn btn-success" id="guardar_orden_de_pago" type="button" disabled="disabled" >guardar</button>
					<button class="btn btn-success" id="cerrar" type="button">cerrar</button>
				</li>
			</ul>
		</form>
</div>


<div id="fondo_descuento" class="hidden">			
		<section id="" class="">
		<form>
			<ul>

				<li  id="descuentos" >
					<div id="titulo_descuentos"> descuentos </div>
					
					<div id="cont_descu">
					<label>Pronto pago</label> 
					<input type="integer" id="des_pron_pago" value="0">
					</div>
					<div id="cont_descu"> 
					<label>par dañados</label> 
					<input type="integer" id="des_par_da" value="0">
					</div>
					<div id="cont_descu">
					<label>par faltante</label> 
					<input type="integer" id="des_par_fal" value="0">
					</div>
					<div class="libtn ">
					<button class="btn btn-success" id="guardar_descuentos" type="button" >guardar</button>
					<button class="btn btn-success" id="cerrar_descuento_modal" type="button">cerrar</button>
					</div>
				</li>

			</ul>
		</form>
	</div>
		</section>
</div>


<div id="fondo_banco" class="hidden">			
	
		<form>
			<ul id="bancoss">

				

			</ul>
		</form>
	</div>
	
</div>