
<div class="col-md-12">
<div class="col-md-12 banner-agencia">
		<img class="banner-agencia" alt=""  src="<?php echo BASE_URL?>/public/img/fotos/banner.jpg" title=""  />
</div>

<div class="col-md-3">
	<div class="row">


		 <div id="datos" class=" col-md-12 xx">
							<address>
							<strong><h2>El Aren de Ruby: </h2></strong>
					
							<span class="glyphicon glyphicon-earphone negro" id="negro"></span>
							<abbr title="Phone"></abbr> 04248486869

							<br><strong><b>Localidad:</b></strong>
							<abbr title="Localidad"></abbr> Direccion
							<br><br>

						

							<a href="bbm" target="_blank"><img alt="" height="32" src="<?php echo BASE_URL?>/public/img/bbm.png" title="Hablemos por BBM: " width="32" /></a><b>56GFS231</b><br>
					
							<a href="whatsapp" target="_blank"><img alt="<?php echo $this->datos['whatsapp'] ?>" height="32" src="<?php echo BASE_URL?>/public/img/whatsapp.png" title="Hablemos por WhatsApp: <?php echo $this->datos['whatsapp'] ?>" width="32" /></a><b>0424-8986869</b><br>

							<a href="facebook" target="_blank"><img alt="" height="32" src="<?php echo BASE_URL?>/public/img/face.png" title="Sígueme en Facebook: " width="32" /></a><b>El Aren de Ruby</b><br>

							<br>
							<strong>E-Mail</strong><br>	
							<span class='glyphicon glyphicon-envelope negro'></span>
							<a href="mailto:#">CORREO</a>
							
		 </div>
	</div>


</div>
<div class="col-md-9">
		
				<div class="promedio">

						
					
							<label class="estrella">&#9733;</label>
							<label class="valor_rating">4,78 Pts</label>

						
				</div>

				<div class="preview_agencia">

						
					
							<center><label class="prev"><h2>Vivir Para Cojer, Cojer Para Vivir, Nuestros Rubies Te Haran Sentir de Maravilla</h2></label></center>

						
				</div>

				<div class="contamos">
				<strong>Contamos con:</strong><br>	
							<img class="color_imagen" alt="" height="32" src="<?php echo BASE_URL?>/public/img/femenino.png" title="femenino" width="32" />damas:<span class="badge"></span> -

							<img class="color_imagen" alt="" height="32" src="<?php echo BASE_URL?>/public/img/masculino.png" title="masculino" width="32" />caballeros:<span class="badge"></span> - 
							<img class="color_imagen" alt="" height="38" src="<?php echo BASE_URL?>/public/img/trans.png" title="trans" width="32" />trans:<span class="badge"></span>
							</address>
				</div>

</br>


</div>
  



 

</div>

<div class="col-md-12">
		
			<div class="col-md-12 vista_ninas">
				<ul>

					<li>
						<div id="prevista" class="listado_chicas">
							 <img id="fotoG"  src="<?php echo BASE_URL?>/public/img/fotos/1.jpg" >
						</div>
					</li>

					<li>
						<div id="prevista" class="listado_chicas">
							 <img id="fotoG"  src="<?php echo BASE_URL?>/public/img/fotos/1.jpg" >
						</div>
					</li>

					<li>
						<div id="prevista" class="listado_chicas">
							 <img id="fotoG"  src="<?php echo BASE_URL?>/public/img/fotos/1.jpg" >
						</div>
					</li>

					<li>
						<div id="prevista" class="listado_chicas">
							 <img id="fotoG"  src="<?php echo BASE_URL?>/public/img/fotos/1.jpg" >
						</div>
					</li>

					<li>
						<div id="prevista" class="listado_chicas">
							 <img id="fotoG"  src="<?php echo BASE_URL?>/public/img/fotos/1.jpg" >
						</div>
					</li>

					</ul>

			</div>
		
</div>


	
				<?php print_r($this->agencias) ?>	
	



	
</div>

