

<div class="col-md-12">


<div class="buscar-agencias-div">
    

      <div class="input-group">
      <input type="text" class="form-control buscaragencia" id="agencia_name" name="agencia_name" placeholder="Buscar">

      <span class="input-group-btn">
        <button class="btn btn-danger" id="btn_buscar" type="button"><span class="glyphicon glyphicon-search"></span></button>
      </span>

          </div><!-- /input-group -->
<input type="hidden"  id="bn" name="bn" value="1" >

</div>



					<?php 

						if(count($this->agencias) == 0){ ?>

						
							<div class="col-md-10 col-md-offset-1 texto-mensaje"> <b> No existen registros. </b></div>

					
					<?php	} else{

		for ($i=0; $i <count($this->agencias) ; $i++) : ?>
		
			
				
				<div class="contenedor-img   agencias-banner-listado" data-id="<?php echo $this->agencias[$i]['id_agencia'] ?>">

					<a href="#"  id="ver_agencia" data-id="<?php echo $this->agencias[$i]['id_agencia'] ?>">
						<img id="img-agencias"  src="<?php echo BASE_URL;?>public/img/fotos/<?php echo $this->agencias[$i]['foto'][0]['nombre_foto'] ?>"></img>
						<div class="mascara">  
				         		<h2><?php echo $this->agencias[$i]['nombre_agencia'] ?></h2>  
				         		
				      
				         		
						
				<div class="pie-agencia">

				<div class="col-md-1 col-sm-1 col-xs-6">
					
					<label class="estrella"> &#9733; <?php echo round($this->agencias[$i]['puntos'],2) ?>Pts</label>

				</div>
				<div class="col-md-4 col-sm-4 col-xs-6 descripcion-agencia">
					 <?php echo $this->agencias[$i]['preview'] ?>
				</div>
				         			

					<?php if ($this->agencias[$i]['pin_agencia']!=""): ?>
					
						<div class="col-md-1 col-sm-1 hidden-xs">
							<a href="bbm" target="_blank"><img alt="<?php echo $this->agencias[$i]['pin_agencia_agencia'] ?>"  src="<?php echo BASE_URL?>/public/img/bbm.png" title="Hablemos por BBM: <?php echo $this->agencias[$i]['pin_agencia'] ?>"  /></a>
						
					</div>
					
					<?php endif ?>

					<?php if ($this->agencias[$i]['whatsapp_agencia']!=""): ?>
					
						<div class="col-md-1 col-sm-1 hidden-xs">
					<a href="whatsapp" target="_blank"><img alt="<?php echo $this->agencias[$i]['whatsapp_agencia'] ?>"  src="<?php echo BASE_URL?>/public/img/whatsapp.png" title="Hablemos por WhatsApp: <?php echo $this->agencias[$i]['whatsapp_agencia'] ?>"  /></a>
					</div>
					<?php endif ?>



					<?php if ($this->agencias[$i]['facebook_agencia']!=""): ?>
					
						<div class="col-md-1 col-sm-1 hidden-xs">
					<a href="facebook" target="_blank"><img alt="<?php echo $this->agencias[$i]['facebook_agencia'] ?>"  src="<?php echo BASE_URL?>/public/img/face.png" title="Sígueme en Facebook: <?php echo $this->agencias[$i]['facebook_agencia'] ?>"  /></a>
					</div>
					<?php endif ?>

							<div class="col-md-4  col-sm-4  col-xs-12 contarores">
					damas:<span class="badge"><?php echo $this->agencias[$i]['total']["damas"]['cantidad'] ?></span>
					caballeros:<span class="badge"><?php echo $this->agencias[$i]['total']['caballeros']['cantidad'] ?></span>
					trans:<span class="badge"><?php echo $this->agencias[$i]['total']['trans']['cantidad'] ?></span>
					</div>



				         		</div>
				         		</div>
					</a>
				</div>
			
		<?php endfor; } ?>
					
		</div>

	





