

<div class="col-md-12">


<div class="buscar-agencias-div">

<div class="texto-busqueda">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos, dignissimos, quidem. Itaque quo quasi natus illo aspernatur nulla atque odio temporibus repellat doloribus eos, inventore, obcaecati excepturi eligendi enim beatae.</div>
	 
	<div class="form-group">
            <label class="col-md-1 alineado" for="">Buscar</label>
            <div class="col-md-11">
            <input type="text" class="form-control" id="agencia_name" name="agencia_name" placeholder=""> 	
            <input type="hidden"  id="bn" name="bn" value="1" > 	
            </div>
            <div class="col-md-12">
				<center><a  class="btn btn-default" id="btn_buscar" href="#">BUSCAR</a> </center> 
		</div>
           
       </div>
      

</div>



	

		<?php for ($i=0; $i <count($this->agencias) ; $i++) : ?>
		
			
				
				<div class="contenedor-img  agencias-banner-listado">

					<a href="#"  id="ver_agencia" data-id="<?php echo $this->agencias[$i]['id_agencia'] ?>">
						<img id="img-agencias"  src="<?php echo BASE_URL;?>public/img/fotos/<?php echo $this->agencias[$i]['foto'][0]['nombre_foto'] ?>"></img>
						<div class="mascara">  
				         		<h2><?php echo $this->agencias[$i]['nombre_agencia'] ?></h2>  
				         		
				      
				         		
						</div>
				<div class="pie-agencia">

				<div class="col-sm-2">
				<label class="puntos" for="radio1">4.9</label>
					<label class="estrella" for="radio1">&#9733;</label>
					<label class="estrella" for="radio1">&#9733;</label>
					<label class="estrella" for="radio1">&#9733;</label>
					<label class="estrella" for="radio1">&#9733;</label>
					<label class="estrella" for="radio1">&#9733;</label>


				</div>
				<div class="col-sm-4 descripcion-agencia">
					 <?php echo $this->agencias[$i]['preview'] ?>
				</div>
				         			

					<?php if ($this->agencias[$i]['pin_agencia']!=""): ?>
					
						<div class="col-sm-1">
							<a href="bbm" target="_blank"><img alt="<?php echo $this->agencias[$i]['pin_agencia_agencia'] ?>" height="32" src="<?php echo BASE_URL?>/public/img/bbm.png" title="Hablemos por BBM: <?php echo $this->agencias[$i]['pin_agencia'] ?>" width="32" /></a>
						
					</div>
					
					<?php endif ?>

					<?php if ($this->agencias[$i]['whatsapp_agencia']!=""): ?>
					
						<div class="col-sm-1">
					<a href="whatsapp" target="_blank"><img alt="<?php echo $this->agencias[$i]['whatsapp_agencia'] ?>" height="32" src="<?php echo BASE_URL?>/public/img/whatsapp.png" title="Hablemos por WhatsApp: <?php echo $this->agencias[$i]['whatsapp_agencia'] ?>" width="32" /></a>
					</div>
					<?php endif ?>



					<?php if ($this->agencias[$i]['facebook_agencia']!=""): ?>
					
						<div class="col-sm-1">
					<a href="facebook" target="_blank"><img alt="<?php echo $this->agencias[$i]['facebook_agencia'] ?>" height="32" src="<?php echo BASE_URL?>/public/img/face.png" title="Sígueme en Facebook: <?php echo $this->agencias[$i]['facebook_agencia'] ?>" width="32" /></a>
					</div>
					<?php endif ?>

							<div class="col-sm-3 contarores">
					damas:<span class="badge"><?php echo $this->agencias[$i]['total']["damas"]['cantidad'] ?></span>
					caballeros:<span class="badge"><?php echo $this->agencias[$i]['total']['caballeros']['cantidad'] ?></span>
					trans:<span class="badge"><?php echo $this->agencias[$i]['total']['trans']['cantidad'] ?></span>
					</div>



				         		</div>
					</a>
				</div>
			
		<?php endfor; ?>
					
		</div>

	





