<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
	<div class="header-titulos">proveedor</div>

<article class="nohaymensaje">
	
	<font>
		ups...¡ no se encontro ningun registro.
	</font>
	<br>	
	<font>
		para agregar proveedores haga <a href="<?php echo BASE_URL ?>proveedor/formu_agregar"> click aqui¡¡</a>
	</font>
	

</article>
	
</div>