<div class="row">

<div class="col-md-8 col-md-offset-2">
	
<div id="foto_grande " class="col-md-12 center-border" style="position: static; margin-left: 15px;" >
<a id="ver_perfil"><h1 class="dorado tex-col">Perfil</h1></a>
</div>



	
	<div class="col-md-8">
		<div class="col-md-1" id="boton_izquierda">
  			<a id="mover" data-mover="izquierda"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span></a>
		</div>
		<div class="col-md-10" style="z-index: 1;">
			<img id="fotoG" class="img img-responsive" src="<?php echo BASE_URL?>/public/img/fotos/1.jpg" />
		</div>
		<div class="col-md-1" id="boton_derecha">
  			<a id="mover" data-mover="derecha"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a>
		</div>
		
	</div>
	<div class="col-md-4">
		<div id="perfil" class="perfil">
			<address>
			<strong>Twitter, Inc.</strong><br>
			1355 Market Street, Suite 900<br>
			San Francisco, CA 94103<br>
			<abbr title="Phone">P:</abbr> (123) 456-7890
			</address>

			<address>
			<strong>Full Name</strong><br>
			<a href="mailto:#">first.last@example.com</a>
			</address>
		</div>
	</div>
	<div class="col-md-12">
		<div>
			
			
			<div id="prevista" class="prviuw">
			<img id="1" class="" width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/1.jpg" >
			</div>
			<div id="prevista" class="prviuw">
			<img id="2" class="" width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/2.jpg" >
			</div>
			<div id="prevista" class="prviuw">
			<img id="3" class="" width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/3.jpg" >
			</div>
			<div id="prevista" class="prviuw">
			<img id="4" class="" width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/4.jpg" >
			</div>
			<div id="prevista" class="prviuw">
			<img id="5" class="" width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/5.jpg" >
			</div>
			<div id="prevista" class="prviuw">
			<img id="6" class="" width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/6.jpg" >
			</div>

		</div>
	</div>



</div>
</div>	



