

<div class="col-md-10 col-md-offset-1">
	
<div id="foto_grande " class="col-md-12 center-border margen_vista_nina"  style="position: static; margin-left: 15px;" >
<a id="ver_perfil"><h1 class="dorado tex-col">Perfil de Andrea</h1></a>
</div>



	
<div class="col-md-6">
		

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img id="fotoG"  class="d-block img-fluid"  src="<?php echo BASE_URL?>/public/img/fotos/1.jpg" >
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <img id="fotoG" class="d-block img-fluid" " src="<?php echo BASE_URL?>/public/img/fotos/2.jpg" >
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <img id="fotoG" class="d-block img-fluid" " src="<?php echo BASE_URL?>/public/img/fotos/3.jpg" >
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <img id="fotoG" class="d-block img-fluid" " src="<?php echo BASE_URL?>/public/img/fotos/4.jpg" >
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <img id="fotoG" class="d-block img-fluid" " src="<?php echo BASE_URL?>/public/img/fotos/7.jpg" >
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <img id="fotoG" class="d-block img-fluid" " src="<?php echo BASE_URL?>/public/img/fotos/6.jpg" >
      <div class="carousel-caption">
        
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>



	
	</div>
	<div class="col-md-6">
		<div class="row">
			<div class="col-md-6">
				<div id="perfil" class="perfil">
					<address>
					<div class="panel-title"><strong> Mis Características Físicas: </strong><br>
					<div class="marco-desc">
					<b>Edad:</b> 19 Años<br>
					<b>Estatura:</b> 1,56 mts<br>
					<b>Peso:</b> 47 kgs<br>
					<b>Medidas:</b> 90-60-90 kgs<br>
					<b>Color de Ojos:</b> Marrones<br>
					<b>Color de Piel:</b> Blanca<br>
					<b>Color de Cabello:</b> Negro<br>
					</div></div>
					<br>
					<div class="panel-title"><strong> Mis Habilidades: </strong><br>
					<div class="marco-desc">
					<b>Destrezas:</b> Contorsionista.<br>
					<b>Especialidad:</b> Hindu, Ruso, Frances, Tailandes, Fetichismo.<br>
					</div></div>
					</address>

				</div>
			</div>
			<div class="col-md-6">
				<div id="perfil" class="perfil">
					<address>
					<div class="panel-title"><strong> Preview: </strong><br>
					<div class="marco-desc">
						Andrea es una chica traviesa, le gusta jugar en la ducha, es contorsionista y le gusta demostrarlo.
					</div></div>
					</address>
					<address>
					<div class="panel-title"><strong>Atiendo A:</strong><br>
					<div class="marco-desc">
						Hombres y Parejas<br>
					</div></div>
					</address>

					<address>
					<div class="panel-title"><strong>Horario de Trabajo:</strong><br>
					<div class="marco-desc">
						24 Horas<br>
					</div></div>
					</address>
				</div>
			</div>

		</div>
	</div>
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-9 margen_vista_nina">
				<ul>
					<li data-target="#carousel-example-generic" data-slide-to="0" class="active">
						<div id="prevista" class="prviuw">
							<img width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/1.jpg" >
						</div>
					</li>

					 <li data-target="#carousel-example-generic" data-slide-to="1"><div id="prevista" class="prviuw">
				<img  width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/2.jpg" >
				</div></li>
					    <li data-target="#carousel-example-generic" data-slide-to="2"><div id="prevista" class="prviuw">
				<img  width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/3.jpg" >
				</div></li>
				<li data-target="#carousel-example-generic" data-slide-to="3" class="active"><div id="prevista" class="prviuw">
				<img width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/4.jpg" >
				</div></li>
					    <li data-target="#carousel-example-generic" data-slide-to="4"><div id="prevista" class="prviuw">
				<img  width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/7.jpg" >
				</div></li>
				<li data-target="#carousel-example-generic" data-slide-to="5"><div id="prevista" class="prviuw">
				<img  width="100px" height="100px" src="<?php echo BASE_URL?>/public/img/fotos/6.jpg" >
				</div></li>
					 </ul>

			</div>
			<div class="col-md-3">

				<div id="contacto">
					<address>
					<strong>Contactame: </strong><br>
					<span class="glyphicon glyphicon-earphone negro" id="negro"></span>
				
					<abbr title="Phone"></abbr> (+58) 414-123-7890
					<br>
					<br>
					<a href="URL-Instagram" target="_blank"><img alt="@andrealc" height="32" src="<?php echo BASE_URL?>/public/img/ig.png" title="sígueme en Instagram: @andrealc" width="32" /></a>
					
					<a href="bbm" target="_blank"><img alt="5CF82B34" height="32" src="<?php echo BASE_URL?>/public/img/bbm.png" title="Hablemos por BBM: 5CF82B34" width="32" /></a>

					<a href="whatsapp" target="_blank"><img alt="+584141237890" height="32" src="<?php echo BASE_URL?>/public/img/whatsapp.png" title="Hablemos por WhatsApp: +58-414-123-7890" width="32" /></a>

					<a href="twitter" target="_blank"><img alt="@andrealc" height="32" src="<?php echo BASE_URL?>/public/img/twitter.png" title="Sígueme en Twitter: @andrealc" width="32" /></a>

					<a href="facebook" target="_blank"><img alt="Andrea Traviesa" height="32" src="<?php echo BASE_URL?>/public/img/face.png" title="Sígueme en Facebook: Andrea Traviesa" width="32" /></a>

				</div>
				

			</div>
		</div>

		<div class="col-md-12">
				<div class="row">
					<div class="col-md-9">
						<div class="row">
							  <div class="califica">
							  <form action="" method="post">
							  	 <label class="califica"><center><address><strong>¿Ya Conoces a Andrea? dale una puntuación a tu experiencia con ella.</strong></address></center></label> <br>
								<pa class="clasificacion">
									<input id="radio1" type="radio" name="estrellas" value="5">
									<label class="estrella" for="radio1">&#9733;</label>

									<input id="radio2" type="radio" name="estrellas" value="4">
									<label class="estrella" for="radio2">&#9733;</label>

									<input id="radio3" type="radio" name="estrellas" value="3">
									<label class="estrella" for="radio3">&#9733;</label>

									<input id="radio4" type="radio" name="estrellas" value="2">
									<label class="estrella" for="radio4">&#9733;</label>

									<input id="radio5" type="radio" name="estrellas" value="1">
									<label class="estrella" for="radio5">&#9733;</label>
								</pa> 
								</form>
								</div>
							</div>
						</div>
					<div>
				</div>
				
				<div class="col-md-3">
					<div class="row">
						<div id="contacto">
							<address>
							<strong>E-Mail</strong><br>
							<span class='glyphicon glyphicon-envelope negro'></span>
							<a href="mailto:#">andreatraviesa@gmail.com</a>
							</address>
						</div>
					</div>

				</div>
				</div>
		</div>	


	</div>



</div>




