<div class="col-xs-12">

<div class="alert-danger title-aviso title1"> <h4 class="title-termino"><center> <b> Bienvenido a OrienteX </b></center> </h4></div>

    <div class="row">
   
	<div class="col-md-10 col-md-offset-1 ">
	<h4 class="texto-top30"><center> <b> OrienteX.com.ve es un sitio exclusivamente dedicado a la publicidad para mayores de 18 años. <br> Este sitio estara online en: <br> 
	<span id="counter">
	<script type="application/javascript">

	var myCountdownTest = new countdown({
									// I'm cheating here... so I don't have to update this every year!
									// year : 2042, // <-- This is a better example of what to use.
								 	year: (new Date().getFullYear() + 1),
									month	: 4, 
									day		: 1,
									width	: 300, 
									height	: 50
									});



	</script>
	</span> </b></center> </h4>
	
			</div>
			</div>
              
    
        



</div>