<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
<div class="header-titulos">administrar menuss</div>

	<div class="col-xs-12 col-md-6">

		<table class="table ">
		<tr class="active">
		<td>id</td>
		<td>titulo</td>
		<td>enlace</td>
		</tr>
		<?php for ($i=0; $i < count($this->menus); $i++): ?>
		<tr>
		<td><?php echo $this->menus[$i]['id_menu'] ?></td>
		<td><?php echo $this->menus[$i]['titulo'] ?></td>
		<td><?php echo $this->menus[$i]['enlace'] ?></td>	
		</tr>
		<?php endfor; ?>
		</table>

</div>
	<div class="col-xs-12 col-md-6">
		
		<table class="table ">
		<tr class="active">
		<?php for ($i=0; $i < count($this->rol); $i++): ?>
		
		<td><?php echo $this->rol[$i]['role'] ?></td>
		
		<?php endfor; ?>
		</tr>
		<?php for ($i=0; $i < count($this->menus) ; $i++): ?>
		<tr>
			<?php for ($x=0; $x < count($this->rol) ; $x++): ?>
			<td> <input id="permisos_ch" <?php echo $retVal = ($this->matris[$i][$x]['permiso']=="1") ? "checked" : "" ; ?> type="checkbox" data-menu="<?php echo $this->menus[$i]['id_menu'] ?>" data-rol="<?php echo $this->rol[$x]['id_role'] ?>"></td>
			<?php endfor; ?>

		</tr>
		<?php endfor; ?>
		</table>


	</div>
	<div class="header-titulos col-xs-12"> ADMINISTAR PAGO</div>
	<div class="col-md-12">
		<center><input class="form-control" type="text" id="buscar_chicas"></center>
	</div>
	<div class="col-md-12" id="div_contenedor2">
		
	</div>


	<div class="col-xs-12">
		<?php for ($i=0; $i < count($this->views) ; $i++): ?>

			<?php echo $this->views[$i].'<br>'; ?> 

		<?php endfor; ?>
	</div>

	<div class="col-xs-12 well">

	<table class="table table-bordered">
		<tr><td id="log_cen" colspan="6">log del sistema</td></tr>
		<tr>
		<td>ip</td>
		<td>id_usuario</td>
		<td>controlador</td>
		<td>metodo</td>
		<td>fecha</td>
		<td>hora</td>
		</tr>

		<?php for ($i=0; $i < count($this->logs) ; $i++): ?>

		<tr>
		<td><?php echo $this->logs[$i]['ip'] ?></td>
		<td><?php echo $this->logs[$i]['id_usuario'] ?></td>
		<td><?php echo $this->logs[$i]['controlador'] ?></td>
		<td><?php echo $this->logs[$i]['metodo'] ?></td>
		<td><?php echo $this->logs[$i]['fecha'] ?></td>
		<td><?php echo $this->logs[$i]['hora'] ?></td>
		</tr>


		<?php endfor; ?>

	</table>

		
		
	</div>


</div>





<div class="modal fade" tabindex="-1" id="modalpago" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="modal-dialog" role="document">
  <input type="text" hidden id="id_chica_pago">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel">Realizar Pago</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12"> 
          	<select id="meses" class="form-control">
          		<option>--Seleccione--</option>
          		<option value="1">1 mes</option>
          		<option value="3">3 meses</option>
          		<option value="6">6 meses</option>
          	</select>
          </div>
        </div>        
      </div>
      <div class="modal-footer">
        <button type="button" id="pago" class="btn btn-primary">Guardar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>




