<div class="page-header">
  <h1>www.CumanaX.com <small>servicios especiales</small></h1>
</div>

<div id="fondo-bolcked" class=" col-xs-12">

	<div class="col-xs-8 col-md-4 col-sm-5 col-md-offset-6 col-sm-offset-6 col-xs-offset-2 mensaje-al-usuario">


		<div class="titulo-mesaje-usuario">AVISO</div>
		<p>

			Esta pagina contiene contenido sexual que no puden ser presenciados por <b>niños, niñas y adolecentes.</b> 
			<br>
			Para <b> www.cumanax.com.ve </b> es muy importante restringir el aceso a menores de edad por esa razon es necesario la validacion de susdatos para que pueda disfrutar de nuetros servicios.
			<br>
			Complete el sigiente formulario para disfrutar de <b>www.cumanax.com.ve</b>
			<br>
			<b>NOTA:</b>
			Toda informacion aqui suministrada estara sujeta a total discrecion de parte de <b>www.cumanax.com</b> y no sera divulgada de ninguna manera.
		</p>

		<div class="row botoness_bloch">
			<div class="">login</div>
			<div id="comprovar" class="">comprovar</div>
			<div class="">regitrarme</div>
		</div>


	</div>
	<div class="col-md-4 col-md-offset-6 validar-al-usuario ">


		<div class="titulo-mesaje-usuario">AVISO</div>
		<p>

			Esta pagina contiene contenido sexual que no puden ser presenciados por <b>niños, niñas y adolecentes.</b> 
			
		</p>

		 <div>
			<form class="form-horizontal">
				  <div class="form-group">
				    <label for="" class="col-sm-2 control-label">Cedula</label>
				    <div class="col-sm-10">
				      <input type="text" class="form-control" id="cedula" placeholder="Cedula">
				    </div>
				  </div>
				   <div class="form-group">
				    <center>
				    	
				    	 <button type="button" class="btn btn-default" id="verificar">verificar</button>
				    	 <button type="button" class="btn btn-default" id="comprovar_atras">atras</button>
				    </center>
				    
				    
				  </div>
			</form>
		</div> 
		
	


	</div>

</div>
<div class="">




  <div class="col-md-4">
    <div class="thumbnail">
      <img class="img-responsive" src="<?php echo BASE_URL."public/img/xxx.jpg" ?>" alt="...">
      <div class="caption">
        <h3>Katiusca</h3>
        
      </div>
    </div>
  </div>
   <div class="col-md-4">
    <div class="thumbnail">
      <img class="img-responsive" src="<?php echo BASE_URL."public/img/xxx1.jpg" ?>" alt="...">
      <div class="caption">
        <h3>Veronica</h3>
        
      </div>
    </div>
  </div>
   <div class="col-md-4">
    <div class="thumbnail">
      <img class="img-responsive" src="<?php echo BASE_URL."public/img/xxx2.jpg" ?>" alt="...">
      <div class="caption">
        <h3>Nicol</h3>
      
      </div>
    </div>
  </div>
</div>