
<div id="fondo-bolcked" class=" col-xs-12">

	<div class="col-xs-8 col-md-4 col-sm-5 col-md-offset-6 col-sm-offset-6 col-xs-offset-2 mensaje-al-usuario">


		<div class="titulo-mesaje-usuario">AVISO</div>
		<p>

			Esta pagina contiene contenido sexual que no puden ser presenciados por <b>niños, niñas y adolecentes.</b> 
			<br>
			Para <b> www.cumanax.com.ve </b> es muy importante restringir el aceso a menores de edad por esa razon es necesario la validacion de susdatos para que pueda disfrutar de nuetros servicios.
			<br>
			Complete el sigiente formulario para disfrutar de <b>www.cumanax.com.ve</b>
			<br>
			<b>NOTA:</b>
			Toda informacion aqui suministrada estara sujeta a total discrecion de parte de <b>www.cumanax.com</b> y no sera divulgada de ninguna manera.
		</p>

		<div class="row botoness_bloch">
			<div id="login">Entrar</div>
			<div id="" class="md-trigger" data-modal="modal-1">Comprobar</div>
			<div id="registrarme">Registrarme</div>
		</div>


	</div>
	<div class="col-md-4 col-md-offset-6 validar-al-usuario ">


		<div class="titulo-mesaje-usuario">AVISO</div>
		<p>

			Esta pagina contiene contenido sexual que no puden ser presenciados por <b>niños, niñas y adolecentes.</b> 
			
		</p>

		 <div>
			
		</div> 
	</div>


		<div class="md-modal md-effect-13" id="modal-1">
			<div class="md-content">
				<h3>Verificando Sus Datos</h3>
				<div>
					<p>Complete el siguiente formulario</p>
						
											
					<div class="row">
					  
					  <div class="col-xs-7">
					    <input type="text" id="cedula"  class="form-control" placeholder="Cedula">
					  </div>
					  <div class="col-xs-4">
					   <button data-modal="modal-2"  id="verificar" class="unico_booton  md-trigger ">Verificar</button>
					  </div>
					</div>
											
					<button class="md-close">Cerrar</button>
				</div>
			</div>
		</div>

		<div class="md-modal md-effect-6" id="modal-2">
			<div class="md-content">
				<h3>Verificando...</h3>
				<div>
					<p></p>
						
											
					<div class="row" id="info">
					  
					 <center>
					 	<img id="img_gif" width="20px" height="20px" src="<?php echo BASE_URL ?>public/img/loading.gif" alt="">
					 </center>
					  <div>
					  <center>
					 	Cargando...
					 </center>		
					</div>
					</div>
											
					<button id="iniciar">Ok</button>
				</div>
			</div>
		</div>
		



<div class="md-overlay"></div>



</div>
<div class="">




  <div class="col-md-4">
    <div class="thumbnail">
      <img class="img-responsive" src="<?php echo BASE_URL."public/img/xxx.jpg" ?>" alt="...">
      <div class="caption">
        <h3>Katiusca</h3>
        
      </div>
    </div>
  </div>
   <div class="col-md-4">
    <div class="thumbnail">
      <img class="img-responsive" src="<?php echo BASE_URL."public/img/xxx1.jpg" ?>" alt="...">
      <div class="caption">
        <h3>Veronica</h3>
        
      </div>
    </div>
  </div>
   <div class="col-md-4">
    <div class="thumbnail">
      <img class="img-responsive" src="<?php echo BASE_URL."public/img/xxx2.jpg" ?>" alt="...">
      <div class="caption">
        <h3>Nicol</h3>
      
      </div>
    </div>
  </div>
</div>