<div class="row">
			<div style="width:1200px;height:800px; margin:40px auto;">
					
					<?php for ($i=0; $i <30 ; $i++) : ?>
					
						<div class="contenedor-img chicas">
						<a href="#"><img width="<?php echo rand(300, 450) ?>" height="<?php echo rand(250,300) ?>" src="<?php echo BASE_URL;?>public/img/fotos/<?php echo $i+1;?>.jpg"></img></a>
						<div class="mascara">  
         				<h2>Andrea</h2>  
         				<p>Andrea es una chica traviesa, le gusta jugar en la ducha, es contorsionista y le gusta demostrarlo.</p>
         				<a href="#" class="link">Ver Más</a>  
						</div>
						</div>

					<?php endfor; ?>
					
				

				</div>
			</div>
		 