
			<div class="col-md-8 col-md-offset-2">
			explicacion o eslogan alucibo a que este es el top-30 de las chicas mas botadas.
			<br>
			<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti voluptatum quos quo suscipit obcaecati illum accusantium fugit, voluptas, enim expedita est officia, modi non numquam earum possimus maxime aperiam quae?</div>
			<div style="width:1200px;height:800px; margin:40px auto;">
				<div class="am-container" id="am-container">


					<?php for ($i=0; $i <count($this->todos) ; $i++) : ?>
					
						<div class="contenedor-img chicas">
							<a href="#"><img width="<?php echo rand(300, 450) ?>" height="<?php echo rand(250,300) ?>" src="<?php echo BASE_URL;?>public/img/fotos/<?php echo $this->todos[$i]['fotos'][0]['nombre_foto'];?>"></img></a>
								<div class="mascara">  
			         				<h2><span># <?php echo $i+1 ?></span> <?php echo $this->todos[$i]['nombre_chicas'] ?></h2>  
			         				<p><?php echo $this->todos[$i]['preview'] ?></p>
			         				<a href="#" id="ver_niña" data-id="<?php echo $this->todos[$i]['id_chicas'] ?>" class="link">Ver Más</a>  
								</div>
						</div>

					<?php endfor; ?>
					
				



     







				</div>
			</div>
		
		
		

